Traceback (most recent call last):
  File "/home/sa7270/diffusion/run_experiment.py", line 44, in <module>
    diffusion.run()
  File "/home/sa7270/diffusion/diffusion.py", line 54, in run
    self.generate_data()
  File "/home/sa7270/diffusion/diffusion.py", line 41, in generate_data
    self.X_train.gen_x1_xt()
  File "/home/sa7270/diffusion/data.py", line 43, in gen_x1_xt
    x_1 = self.s.reshape(self.n,1)@self.Î¼.reshape(1,self.d)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)
